language: python
python:
  - "2.7"
install:
  - "MY_VIRTUAL_ENV=$VIRTUAL_ENV"
  - "deactivate"
  - "virtualenv --clear --python /usr/bin/python $MY_VIRTUAL_ENV"
  - "source $MY_VIRTUAL_ENV/bin/activate"
  - "bash make.sh"
# Run tests for Cheshire3 and archiveshub
script:
  - "bash test.sh"
